name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "15.0"
      - uses: actions/checkout@v2
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Build
        run: set -o pipefail && xcodebuild -scheme "Capturer" -destination 'generic/platform=iOS Simulator' | xcbeautify
